# Generated by Django 5.2.1 on 2025-06-07 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('statut', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('temps_passe', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('RAN', 'RAN'), ('CORE', 'CORE'), ('DRIVE_TEST', 'DRIVE TEST'), ('OPTIMISATION', 'OPTIMISATION')], max_length=50)),
                ('autre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaysAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(choices=[("COTE D'IVOIRE", "COTE D'IVOIRE"), ('BURKINA FASO', 'BURKINA FASO'), ('MALI', 'MALI'), ('BENIN', 'BENIN'), ('GUINEE', 'GUINEE'), ('TOGO', 'TOGO'), ('NIGER', 'NIGER'), ('SENEGAL', 'SENEGAL'), ('GABON', 'GABON'), ('CAMEROUN', 'CAMEROUN'), ('CONGO', 'CONGO'), ('CENTRAFRIQUE', 'CENTRAFRIQUE'), ('TCHAD', 'TCHAD'), ('REPUBLIQUE DEMOCRATIQUE DU CONGO', 'REPUBLIQUE DEMOCRATIQUE DU CONGO')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('nationalite', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_mission', 'En mission'), ('en_disponibilité', 'En disponibilité'), ('en_congé', 'En congé')], default='actif', max_length=50)),
                ('residence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChefProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_projet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponctualite', models.IntegerField()),
                ('respect', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Geequipe.chefprojet')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Geequipe.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_livrable', models.CharField(max_length=100)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='Geequipe.activite')),
            ],
        ),
        migrations.CreateModel(
            name='Mobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('site', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilisations', to='Geequipe.activite')),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilisations', to='Geequipe.chefprojet')),
            ],
        ),
        migrations.CreateModel(
            name='Noter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponctualite', models.IntegerField()),
                ('respect', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='Geequipe.chefprojet')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('monteur', 'Monteur'), ('chauffeur', 'Chauffeur'), ('technicien', 'Technicien')], max_length=20)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='Geequipe.equipe')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Expatriation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expatriation', models.DateField()),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expatriations', to='Geequipe.paysaffectation')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expatriations', to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Effectuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affecter', models.DateField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels_affectes', to='Geequipe.activite')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_effectuees', to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('date_obtention', models.DateField()),
                ('validite', models.DateField()),
                ('statut', models.CharField(max_length=50)),
                ('organisme', models.CharField(max_length=100)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='certificats/')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Posseder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='Geequipe.competence')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_possedees', to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('site', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_attente', 'En attente'), ('suspendu', 'Suspendu')], default='en_cours', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='Geequipe.chefprojet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='Geequipe.client')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_projet', to='Geequipe.equipe')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_affectee', to='Geequipe.projet')),
            ],
        ),
        migrations.AddField(
            model_name='activite',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='Geequipe.projet'),
        ),
        migrations.CreateModel(
            name='Realiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_realisation', to='Geequipe.activite')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_realisees', to='Geequipe.equipe')),
            ],
        ),
    ]
