# Generated by Django 5.2.1 on 2025-06-02 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('statut', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('temps_passe', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('RAN', 'RAN'), ('CORE', 'CORE'), ('DRIVE_TEST', 'DRIVE TEST'), ('AUTRE', 'AUTRE')], max_length=50)),
                ('autre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
                ('date_dissolution', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaysAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(choices=[('CI', 'Côte d’Ivoire'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('SN', 'Sénégal'), ('GN', 'Guinée')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('nationalite', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChefProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffectationProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponctualite', models.IntegerField()),
                ('respect', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.chefprojet')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_livrable', models.CharField(max_length=100)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.activite')),
            ],
        ),
        migrations.CreateModel(
            name='Mobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('site', models.CharField(max_length=100)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.activite')),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.chefprojet')),
            ],
        ),
        migrations.CreateModel(
            name='Noter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponctualite', models.IntegerField()),
                ('respect', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.chefprojet')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('monteur', 'Monteur'), ('chauffeur', 'Chauffeur'), ('technicien', 'Technicien')], max_length=20)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.equipe')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Expatriation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expatriation', models.DateField()),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.paysaffectation')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Effectuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affecter', models.DateField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.activite')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('date_obtention', models.DateField()),
                ('validite', models.DateField()),
                ('organisme', models.CharField(max_length=100)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Posseder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.competence')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('site', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.chefprojet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.client')),
            ],
        ),
        migrations.AddField(
            model_name='activite',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.projet'),
        ),
        migrations.CreateModel(
            name='Realiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.activite')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geequipe.equipe')),
            ],
        ),
    ]
