# Generated by Django 5.2.1 on 2025-06-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geequipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='Geequipe.projet'),
        ),
        migrations.AlterField(
            model_name='affectationprojet',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_projet', to='Geequipe.equipe'),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='Geequipe.personnel'),
        ),
        migrations.AlterField(
            model_name='chefprojet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_projet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='effectuer',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels_affectes', to='Geequipe.activite'),
        ),
        migrations.AlterField(
            model_name='effectuer',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_effectuees', to='Geequipe.personnel'),
        ),
        migrations.AlterField(
            model_name='evaluer',
            name='chef_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Geequipe.chefprojet'),
        ),
        migrations.AlterField(
            model_name='evaluer',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Geequipe.equipe'),
        ),
        migrations.AlterField(
            model_name='expatriation',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expatriations', to='Geequipe.paysaffectation'),
        ),
        migrations.AlterField(
            model_name='expatriation',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expatriations', to='Geequipe.personnel'),
        ),
        migrations.AlterField(
            model_name='livrable',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='Geequipe.activite'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='Geequipe.equipe'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='Geequipe.personnel'),
        ),
        migrations.AlterField(
            model_name='mobilisation',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilisations', to='Geequipe.activite'),
        ),
        migrations.AlterField(
            model_name='mobilisation',
            name='chef_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilisations', to='Geequipe.chefprojet'),
        ),
        migrations.AlterField(
            model_name='noter',
            name='chef_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='Geequipe.chefprojet'),
        ),
        migrations.AlterField(
            model_name='noter',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Geequipe.personnel'),
        ),
        migrations.AlterField(
            model_name='posseder',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='Geequipe.competence'),
        ),
        migrations.AlterField(
            model_name='posseder',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_possedees', to='Geequipe.personnel'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='chef_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='Geequipe.chefprojet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='Geequipe.client'),
        ),
        migrations.AlterField(
            model_name='realiser',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_realisation', to='Geequipe.activite'),
        ),
        migrations.AlterField(
            model_name='realiser',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_realisees', to='Geequipe.equipe'),
        ),
    ]
