# Generated by Django 5.2.1 on 2025-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geequipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectuer',
            name='date_affecter',
            field=models.DateField(auto_now=True),
        ),
    ]
