# Generated by Django 5.2.1 on 2025-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geequipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminé', 'Terminé'), ('planifiée', 'planifiée'), ('suspendue', 'Suspendue')], default='planifiée', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ACTIF', 'Actif'), ('CONGE', 'En congé'), ('SUSPENDU', 'Suspendu'), ('MISSION', 'En mission')], default='actif', max_length=50),
        ),
    ]
