# Generated by Django 5.2.1 on 2025-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geequipe', '0002_alter_activite_statut_alter_personnel_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminée', 'Terminée'), ('planifiée', 'planifiée'), ('suspendue', 'Suspendue')], default='planifiée', max_length=20),
        ),
        migrations.AlterField(
            model_name='activite',
            name='temps_passe',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realiser',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
