from django.contrib import admin
from .models import PaysAffectation, Personnel, ChefProjet, Client, Projet, Equipe, Membre, Competence, Posseder, Activite, Effectuer, Certificat, Realiser, Livrable, Mobilisation, AffectationProjet, Noter, Evaluer, Expatriation

admin.site.register(PaysAffectation)
admin.site.register(Personnel)
admin.site.register(ChefProjet)
admin.site.register(Client)
admin.site.register(Projet)
admin.site.register(Equipe)
admin.site.register(Membre)
admin.site.register(Competence)
admin.site.register(Posseder)
admin.site.register(Activite)
admin.site.register(Effectuer)
admin.site.register(Certificat)
admin.site.register(Realiser)
admin.site.register(Livrable)
admin.site.register(Mobilisation)
admin.site.register(AffectationProjet)
admin.site.register(Noter)
admin.site.register(Evaluer)
admin.site.register(Expatriation)